/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.Book;
import model.Borrower;
import control.BookDAO;
import control.BorrowerDAO;
import control.LoanDAO;
import control.StaffDAO;
import java.io.IOException;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Loan;
import model.Staff;
/**
 *
 * @author lienb
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    private ServerSocket listener;
    private static Client client;
    DefaultTableModel modelBook;
    DefaultTableModel modelBorrower;
    DefaultTableModel modelLoan;
    DefaultTableModel modelStaff;
    private ArrayList<Book> bookList;
    private ArrayList<Borrower> borrowerList;
    private ArrayList<Staff> staffList;
    private ArrayList<Loan> loanList;
    BookDAO bookDAO = new BookDAO();
    BorrowerDAO borrowerDAO = new BorrowerDAO();
    StaffDAO staffDAO = new StaffDAO();
    LoanDAO loanDAO = new LoanDAO();
    private int x = 10;
    //bookList = bookDAO.getInfoAllBook();
    
    public Admin(Client client) {
        initComponents();
        this.client = client;
        bookList = null;
        modelBook = (DefaultTableModel)bookTable.getModel();
        modelBorrower = (DefaultTableModel)borrowerTable.getModel();
        modelStaff = (DefaultTableModel)staffTable.getModel();
        modelLoan = (DefaultTableModel) loanTable.getModel();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        searchTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonSearchBook = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonInsertBook = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buttonDeleteBook = new javax.swing.JButton();
        txtDeleteId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtborrowed = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        buttonAllBook = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        loanTable = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        buttonShowLoan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtSearchBorrower = new javax.swing.JTextField();
        buttonSearchBorrower = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        borrowerTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNameBorrower = new javax.swing.JTextField();
        txtEmailBorrower = new javax.swing.JTextField();
        txtPasswordBorrower = new javax.swing.JTextField();
        txtAddressBorrower = new javax.swing.JTextField();
        txtPhoneBorrower = new javax.swing.JTextField();
        buttonAddBrrower = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtIdDeleteBorrower = new javax.swing.JTextField();
        buttonIdDeleteBrrower = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        buttonShowBrrower = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtSearchStaff = new javax.swing.JTextField();
        buttonSearchStaff = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtNameStaff = new javax.swing.JTextField();
        txtEmailStaff = new javax.swing.JTextField();
        txtPasswordStaff = new javax.swing.JTextField();
        txtAddressStaff = new javax.swing.JTextField();
        txtPhoneStaff = new javax.swing.JTextField();
        txtSalaryStaff = new javax.swing.JTextField();
        buttonAddStaff = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtIdDeleteStaff = new javax.swing.JTextField();
        buttonDeleteStaff = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtSumBook = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtBookBorrowed = new javax.swing.JTextField();
        txtFinePaid = new javax.swing.JTextField();
        txtCountBorrower = new javax.swing.JTextField();
        txtCountStaff = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        buttonSatistic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí thư viện");

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tác giả", "Số lượng", "Đã mượn", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(bookTable);

        jLabel1.setText("Tìm kiếm ");

        buttonSearchBook.setText("Tìm");
        buttonSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchBookActionPerformed(evt);
            }
        });

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên sách");

        jLabel3.setText("Thể loại");

        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });

        jLabel4.setText("Tác giả");

        jLabel5.setText("Tổng số lượng");

        jLabel6.setText("Trạng thái");

        buttonInsertBook.setText("Thêm sách");
        buttonInsertBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertBookActionPerformed(evt);
            }
        });

        jLabel7.setText("Xóa sách theo mã sách");

        buttonDeleteBook.setText("Xóa");
        buttonDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteBookActionPerformed(evt);
            }
        });

        jLabel8.setText("Nhập mã sách cần xóa");

        jLabel12.setText("Đã mượn");

        jLabel13.setText("Hiển thị tất cả các sách");

        buttonAllBook.setText("Hiển thị");
        buttonAllBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(187, 187, 187)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonSearchBook)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel12))
                                    .addGap(17, 17, 17)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtborrowed, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                        .addComponent(buttonInsertBook)
                                                        .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                                    .addGap(0, 425, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel8)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(30, 30, 30)))
                                            .addComponent(buttonDeleteBook)
                                            .addGap(15, 15, 15))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(252, 252, 252)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(41, 41, 41)
                                            .addComponent(buttonAllBook)))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonSearchBook)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDeleteBook)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(buttonAllBook))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtborrowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(buttonInsertBook)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Quản lí sách", jPanel1);

        loanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu mượn", "Tên bạn đọc mượn", "Tên sách mượn", "Nhân viên cho mượn", "Nhân viên nhận sách", "Ngày mượn sách", "Ngày trả sách", "Số tiền phạt"
            }
        ));
        jScrollPane4.setViewportView(loanTable);

        jLabel23.setText("Hiển thị tất cả các phiếu mượn");

        buttonShowLoan.setText("Hiển thị");
        buttonShowLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowLoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel23)
                        .addGap(28, 28, 28)
                        .addComponent(buttonShowLoan)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(buttonShowLoan))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lí mượn sách", jPanel5);

        jLabel9.setText("Tìm kiếm");

        buttonSearchBorrower.setText("Tìm");
        buttonSearchBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchBorrowerActionPerformed(evt);
            }
        });

        borrowerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã bạn đọc", "Tên bạn đọc", "Email", "Mật khẩu", "Địa chỉ", "Số điện thoại"
            }
        ));
        jScrollPane2.setViewportView(borrowerTable);

        jLabel15.setText("Tên bạn đọc");

        jLabel16.setText("Email");

        jLabel17.setText("Mật khẩu");

        jLabel18.setText("Địa chỉ");

        jLabel19.setText("Số điện thoại");

        txtEmailBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailBorrowerActionPerformed(evt);
            }
        });

        buttonAddBrrower.setText("Thêm bạn đọc");
        buttonAddBrrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddBrrowerActionPerformed(evt);
            }
        });

        jLabel20.setText("Xóa bạn đọc theo id");

        jLabel21.setText("Nhập id muốn xóa");

        buttonIdDeleteBrrower.setText("Xóa");
        buttonIdDeleteBrrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIdDeleteBrrowerActionPerformed(evt);
            }
        });

        jLabel22.setText("Hiển thị tất cả thông tin bạn đọc");

        buttonShowBrrower.setText("Hiển thị");
        buttonShowBrrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowBrrowerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel9)
                        .addGap(52, 52, 52)
                        .addComponent(txtSearchBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSearchBorrower))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(buttonAddBrrower))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))
                                        .addGap(280, 280, 280))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPhoneBorrower, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtEmailBorrower)
                                                    .addComponent(txtNameBorrower)
                                                    .addComponent(txtPasswordBorrower)
                                                    .addComponent(txtAddressBorrower))))
                                        .addGap(143, 143, 143)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonShowBrrower))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(jLabel21)
                                .addGap(51, 51, 51)
                                .addComponent(txtIdDeleteBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(buttonIdDeleteBrrower)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSearchBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearchBorrower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtIdDeleteBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonIdDeleteBrrower))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNameBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtEmailBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(buttonShowBrrower))))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPasswordBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtAddressBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtPhoneBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonAddBrrower)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Quản lí bạn đọc", jPanel3);

        jLabel10.setText("Tìm kiếm");

        buttonSearchStaff.setText("Tìm");
        buttonSearchStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchStaffActionPerformed(evt);
            }
        });

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Email", "Mật khẩu", "Địa chỉ", "Số điện thoại", "Tiền lương"
            }
        ));
        jScrollPane3.setViewportView(staffTable);

        jLabel14.setText("Tên nhân viên");

        jLabel29.setText("Email");

        jLabel30.setText("Mật khẩu");

        jLabel31.setText("Địa chỉ");

        jLabel32.setText("Số điện thoại");

        jLabel33.setText("Tiền lương");

        buttonAddStaff.setText("Thêm nhân viên");
        buttonAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddStaffActionPerformed(evt);
            }
        });

        jLabel34.setText("Xóa nhân viên theo mã nhân viên");

        jLabel35.setText("Nhập id: ");

        buttonDeleteStaff.setText("Xóa");
        buttonDeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteStaffActionPerformed(evt);
            }
        });

        jLabel36.setText("Hiển thị tất cả các nhân viên");

        jButton3.setText("Hiển thị");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addGap(33, 33, 33)
                        .addComponent(txtIdDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(buttonDeleteStaff))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(jLabel10)
                            .addGap(81, 81, 81)
                            .addComponent(txtSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonSearchStaff))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel32)
                                        .addComponent(jLabel33))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPasswordStaff)
                                        .addComponent(txtNameStaff)
                                        .addComponent(txtEmailStaff)
                                        .addComponent(txtAddressStaff)
                                        .addComponent(txtPhoneStaff)
                                        .addComponent(txtSalaryStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                                .addComponent(jLabel30))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(jLabel36)
                                    .addGap(33, 33, 33)
                                    .addComponent(jButton3))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel34))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(buttonAddStaff))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearchStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtIdDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDeleteStaff))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(txtEmailStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(txtPasswordStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jButton3))))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(txtAddressStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtPhoneStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtSalaryStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonAddStaff)
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Quản lí nhân viên", jPanel4);

        jLabel24.setText("Tổng số sách");

        jLabel25.setText("Tống số nhân viên");

        jLabel26.setText("Số lượng bạn đọc");

        jLabel27.setText("Doanh thu");

        txtCountBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountBorrowerActionPerformed(evt);
            }
        });

        jLabel11.setText("Số sách đã mượn");

        jLabel28.setText("(Tổng số tiền phạt)");

        buttonSatistic.setText("Thống kê");
        buttonSatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSatisticActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27)
                                .addComponent(jLabel11)
                                .addComponent(jLabel28)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCountStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSumBook, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(txtBookBorrowed)
                                .addComponent(txtFinePaid))
                            .addComponent(txtCountBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(buttonSatistic)))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(buttonSatistic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtSumBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtCountStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtCountBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtFinePaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonShowBrrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowBrrowerActionPerformed
        // TODO add your handling code here:
        // Hien thi tat ca ban doc
        borrowerList = borrowerDAO.getInfoAllBorrower();

        showBorrower(borrowerList);
        borrowerList.clear();

    }//GEN-LAST:event_buttonShowBrrowerActionPerformed

    private void buttonAddBrrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddBrrowerActionPerformed

        // Thêm bạn đọc vào CSDL
        Borrower borrower = new Borrower();
       
        borrower.setName(txtNameBorrower.getText());
        borrower.setEmail(txtEmailBorrower.getText());
        borrower.setPassword(txtPasswordBorrower.getText());
        borrower.setAddress(txtAddressBorrower.getText());
        borrower.setPhone(txtPhoneBorrower.getText());

        int k = borrowerDAO.insertBorrower(borrower);
        if( k == 1){

            // Thông báo đã thêm thành công hay thất bại
            //JOptionPane.showMessageDialog(JFame,"Thêm Sách");

            JOptionPane.showConfirmDialog(null, "Thêm thành công","Thêm bạn đọc",JOptionPane.DEFAULT_OPTION);
        }else if ( k == -1){
            JOptionPane.showConfirmDialog(null, "Trùng id", "Thêm bạn đọc", JOptionPane.DEFAULT_OPTION);
        }else{
            JOptionPane.showConfirmDialog(null, "Không được để trống", "Thêm bạn đọc", JOptionPane.DEFAULT_OPTION);
        }

    }//GEN-LAST:event_buttonAddBrrowerActionPerformed

    private void txtEmailBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailBorrowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailBorrowerActionPerformed

    private void buttonSearchBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchBorrowerActionPerformed

        String keyWordBorrower = txtSearchBorrower.getText();
        System.out.println(keyWordBorrower);
        borrowerList = borrowerDAO.searchBorrowersByKeyword(keyWordBorrower);
        for ( Borrower borrower: borrowerList){
            System.out.println(borrower.getIdPerson()+ " " + borrower.getName());
        }
        showBorrower(borrowerList);
        borrowerList.clear();
    }//GEN-LAST:event_buttonSearchBorrowerActionPerformed

    private void buttonShowLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowLoanActionPerformed
        // TODO add your handling code here:

        loanList = loanDAO.getInfoAllLoan();
        showLoan(loanList);
        loanList.clear();

    }//GEN-LAST:event_buttonShowLoanActionPerformed

    private void txtCountBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountBorrowerActionPerformed
        
        txtCountBorrower.setText(String.valueOf((new BorrowerDAO()).countBorrower()));
       
    }//GEN-LAST:event_txtCountBorrowerActionPerformed

    private void buttonAllBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllBookActionPerformed

        try {
            client.sendMSG("showBook");
            System.out.println("Gửi showBook đến server");
        } catch (IOException ex) {
            System.out.println("Lỗi gửi showBook đến Server");

            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

        String request = null;
        int idbook;
        String title;
        String subject;
        String author;
        int quantitySum;
        int quantityBorrowed;
        String status;

        modelBook.setRowCount(0);
        while ( true){
            try {
                request = client.getMSG();

                if( request.equals("done")){
                    break;
                }
                if(request.equals("book")){

                    idbook = Integer.parseInt(client.getMSG());
                    title = client.getMSG();
                    subject = client.getMSG();
                    author = client.getMSG();
                    quantitySum = Integer.parseInt(client.getMSG());
                    quantityBorrowed = Integer.parseInt(client.getMSG());
                    status = client.getMSG();

                    modelBook.addRow(new Object[]{
                        idbook, title, subject, author, quantitySum, quantityBorrowed, status
                    });

                }

            } catch (IOException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        /*
        bookList = bookDAO.getInfoAllBook();
        showBook(bookList);
        bookList.clear();
        */
    }//GEN-LAST:event_buttonAllBookActionPerformed

    private void buttonDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteBookActionPerformed
        int id = Integer.parseInt(txtDeleteId.getText());
        if(bookDAO.deleteBook(id)){
            JOptionPane.showConfirmDialog(null, "Xóa thành công!", "Xóa sách", JOptionPane.DEFAULT_OPTION);
            System.out.println("Xóa thành công!");
        }else{
            JOptionPane.showConfirmDialog(null, "Xóa thành công!", "Xóa sách", JOptionPane.DEFAULT_OPTION);
            System.out.println("Xóa thất bại!");
        }
    }//GEN-LAST:event_buttonDeleteBookActionPerformed

    private void buttonInsertBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertBookActionPerformed
        // TODO add your handling code here:
        Book book = new Book();
        // book.setIdbook(Integer.parseInt(txtidbook.getText()));
        book.setTitle(txtTitle.getText());
        book.setSubject(txtSubject.getText());
        book.setAuthor(txtAuthor.getText());
        book.setQuantitySum(Integer.parseInt(txtQuantity.getText()));
        book.setQuantityBorrowed(Integer.parseInt(txtborrowed.getText()));
        book.setStatus(txtStatus.getText());

        bookDAO.insertBook(book);

        // Thông báo đã thêm thành công hay thất bại
        //JOptionPane.showMessageDialog(JFame,"Thêm Sách");

        JOptionPane.showConfirmDialog(null, "Thêm thành công","Thêm sách",JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_buttonInsertBookActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void buttonSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchBookActionPerformed
        // TODO add your handling code here:
        String keyWordBook = searchTf.getText();
        System.out.println(keyWordBook);
        bookList = bookDAO.searchBooksByKeyword(keyWordBook);
        for ( Book book: bookList){
            System.out.println(book.getIdbook()+ " " + book.getTitle());
        }
        showBook(bookList);
        bookList.clear();
    }//GEN-LAST:event_buttonSearchBookActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonIdDeleteBrrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIdDeleteBrrowerActionPerformed

        // xóa tài khoản bạn đọc theo id
        int id = Integer.parseInt(txtIdDeleteBorrower.getText());
        if(borrowerDAO.deleteBorrower(id)){
            JOptionPane.showConfirmDialog(null, "Xóa tài khoản bạn đọc thành công!", "Xóa bạn đọc", JOptionPane.DEFAULT_OPTION);
            System.out.println("Xóa thành công!");
        }else{
            JOptionPane.showConfirmDialog(null, "Xóa tài khoản bạn đọc thất bại", "Xóa bạn đọc", JOptionPane.DEFAULT_OPTION);
            System.out.println("Xóa thất bại!");
        }
        
        
    }//GEN-LAST:event_buttonIdDeleteBrrowerActionPerformed

    private void buttonSearchStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchStaffActionPerformed

        // tìm kiếm nhân viên 
        String keyWordStaff = txtSearchStaff.getText();
        System.out.println(keyWordStaff);
        staffList = staffDAO.searchStaffsByKeyword(keyWordStaff);
        showStaff(staffList);
        staffList.clear();
        
        
    }//GEN-LAST:event_buttonSearchStaffActionPerformed

    private void buttonAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddStaffActionPerformed
        // TODO add your handling code here:
        //Thêm nhân viên
        Staff staff = new Staff();
        
       
        staff.setName(txtNameStaff.getText());
        staff.setEmail(txtEmailStaff.getText());
        staff.setPassword(txtPasswordStaff.getText());
        staff.setAddress(txtAddressStaff.getText());
        staff.setPhone(txtPhoneStaff.getText());
        staff.setSalary(Double.parseDouble(txtSalaryStaff.getText()));

        int k = staffDAO.insertStaff(staff);
        if( k == 1){

            // Thông báo đã thêm thành công hay thất bại
            //JOptionPane.showMessageDialog(JFame,"Thêm Sách");

            JOptionPane.showConfirmDialog(null, "Thêm thành công","Thêm bạn đọc",JOptionPane.DEFAULT_OPTION);
        }else{
            JOptionPane.showConfirmDialog(null, "Không được để trống", "Thêm bạn đọc", JOptionPane.DEFAULT_OPTION);
        }
        
        
    }//GEN-LAST:event_buttonAddStaffActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Hiển thị tất cả các nhân viên
        staffList = staffDAO.getInfoAllStaff();
        showStaff(staffList);
        staffList.clear();

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteStaffActionPerformed
        // TODO add your handling code here:
        // Xóa nhân viên theo mã số id
        // xóa tài khoản bạn đọc theo id
        int id = Integer.parseInt(txtIdDeleteStaff.getText());
        if(staffDAO.deleteStaff(id)){
            JOptionPane.showConfirmDialog(null, "Xóa tài khoản nhân viên thành công!", "Xóa nhân viên", JOptionPane.DEFAULT_OPTION);
            System.out.println("Xóa thành công!");
        }else{
            JOptionPane.showConfirmDialog(null, "Xóa tài khoản nhân viên thất bại", "Xóa nhân viên", JOptionPane.DEFAULT_OPTION);
            System.out.println("Xóa thất bại!");
        }
        
    }//GEN-LAST:event_buttonDeleteStaffActionPerformed

    private void buttonSatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSatisticActionPerformed
        // TODO add your handling code here:
        // Thống kê
        txtCountBorrower.setText(String.valueOf((new BorrowerDAO()).countBorrower()));
        txtCountStaff.setText(String.valueOf((new StaffDAO()).countStaff()));
        txtSumBook.setText(String.valueOf((new BookDAO()).sumBook()));
        txtBookBorrowed.setText(String.valueOf((new BookDAO()).sumBookBorrowed()));
        txtFinePaid.setText(String.valueOf((new BookDAO()).sumFinePaid()));
    }//GEN-LAST:event_buttonSatisticActionPerformed
    
    public void clearBookTable(){
        System.out.println("clear book table được gọi");
        modelBook =( DefaultTableModel) bookTable.getModel();
        modelBook.setRowCount(0);
        /*
        int rows = modelBook.getRowCount(); 
        for(int i = rows - 1; i >=0; i--) {
            modelBook.removeRow(i); 
        }
        System.out.println(rows);
*/
    }
    
    public void showBook(ArrayList<Book> bookList){
        //model.setRowCount(0);
        /*
        bookTable.setModel( new DefaultTableModel(null, new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tác giả", "Số lượng","Đã mượn", "Trạng thái"
            }));
        
        modelBook =( DefaultTableModel) bookTable.getModel();
        modelBook.setRowCount(0);
        */
        clearBookTable();
        System.out.println("show Book được gọi");
        int i = 0;
        for ( Book book: bookList){
            System.out.println("i" + (i++));
            int rows = modelBook.getRowCount(); 
            System.out.println("rows: " + rows);
            modelBook.addRow(new Object[]{
                book.getIdbook(), book.getTitle(), book.getSubject(), book.getAuthor(), book.getQuantitySum(), book.getQuantityBorrowed(), book.getStatus()
            });
        }
                    
    }
    
    public void showBorrower(ArrayList<Borrower> borrowerList){
        
        //clearBookTable();
        modelBorrower.setRowCount(0);
        System.out.println("show Borrower được gọi");
        int i = 0;
        for ( Borrower borrower: borrowerList){
            System.out.println("i" + (i++));
            int rows = modelBook.getRowCount(); 
            System.out.println("rows: " + rows);
            modelBorrower.addRow(new Object[]{
                borrower.getIdPerson(), borrower.getName(), borrower.getEmail(), borrower.getPassword(), borrower.getAddress(), borrower.getPhone()
            });
        }
    }
    
    public void showStaff(ArrayList<Staff> staffList){
        modelStaff.setRowCount(0);
        
        for( Staff staff: staffList){
            modelStaff.addRow(new Object[]{
                staff.getIdPerson(),staff.getName(),staff.getEmail(),staff.getPassword(),staff.getAddress(),staff.getPhone(),staff.getSalary()
            });
        }
        
        
    }
        
    /**
     * @param args the command line arguments
     */
    public void showLoan(ArrayList<Loan> loanList){
        modelLoan.setRowCount(0);
        
        for ( Loan loan: loanList){
            modelLoan.addRow(new Object[]{
            loan.getIdLoan(),loan.getBorrower().getName(),loan.getBook().getTitle(),
            loan.getIssuer().getName(), loan.getReceiver().getName(),loan.getIssuedDate(),loan.getReturnedDate(),
            loan.getFinePaid()
            });
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try{
                    
                Admin admin = new Admin(client);
                admin.setVisible(true);
                    
                }catch( Exception e){
                    e.printStackTrace();
                }
        }
        
        
        });
    }
        
     



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookTable;
    private javax.swing.JTable borrowerTable;
    private javax.swing.JButton buttonAddBrrower;
    private javax.swing.JButton buttonAddStaff;
    private javax.swing.JButton buttonAllBook;
    private javax.swing.JButton buttonDeleteBook;
    private javax.swing.JButton buttonDeleteStaff;
    private javax.swing.JButton buttonIdDeleteBrrower;
    private javax.swing.JButton buttonInsertBook;
    private javax.swing.JButton buttonSatistic;
    private javax.swing.JButton buttonSearchBook;
    private javax.swing.JButton buttonSearchBorrower;
    private javax.swing.JButton buttonSearchStaff;
    private javax.swing.JButton buttonShowBrrower;
    private javax.swing.JButton buttonShowLoan;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable loanTable;
    private javax.swing.JTextField searchTf;
    private javax.swing.JTable staffTable;
    private javax.swing.JTextField txtAddressBorrower;
    private javax.swing.JTextField txtAddressStaff;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookBorrowed;
    private javax.swing.JTextField txtCountBorrower;
    private javax.swing.JTextField txtCountStaff;
    private javax.swing.JTextField txtDeleteId;
    private javax.swing.JTextField txtEmailBorrower;
    private javax.swing.JTextField txtEmailStaff;
    private javax.swing.JTextField txtFinePaid;
    private javax.swing.JTextField txtIdDeleteBorrower;
    private javax.swing.JTextField txtIdDeleteStaff;
    private javax.swing.JTextField txtNameBorrower;
    private javax.swing.JTextField txtNameStaff;
    private javax.swing.JTextField txtPasswordBorrower;
    private javax.swing.JTextField txtPasswordStaff;
    private javax.swing.JTextField txtPhoneBorrower;
    private javax.swing.JTextField txtPhoneStaff;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSalaryStaff;
    private javax.swing.JTextField txtSearchBorrower;
    private javax.swing.JTextField txtSearchStaff;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtSumBook;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtborrowed;
    // End of variables declaration//GEN-END:variables
}
